/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author andri
 */
public class PenampilGambarDenganButtonGUI extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarDenganButtonGUI
     */
    public PenampilGambarDenganButtonGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        ButtonPanel = new javax.swing.JPanel();
        glassfishButton = new javax.swing.JButton();
        javaeeButton = new javax.swing.JButton();
        postgresqlButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        ImagePanel = new javax.swing.JPanel();
        GlassfishLabel = new javax.swing.JLabel();
        JavaeeLabel = new javax.swing.JLabel();
        postgreLabel = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        glassfishButton.setText("Glassfish");
        glassfishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassfishButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(glassfishButton);

        javaeeButton.setText("JavaEE");
        javaeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaeeButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(javaeeButton);

        postgresqlButton.setText("PostgreSQL");
        postgresqlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgresqlButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(postgresqlButton);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(exitButton);

        ImagePanel.setLayout(new java.awt.CardLayout());

        GlassfishLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/glassfish.jpg"))); // NOI18N
        ImagePanel.add(GlassfishLabel, "0");

        JavaeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/javaee.jpg"))); // NOI18N
        ImagePanel.add(JavaeeLabel, "1");

        postgreLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/postgresql.jpg"))); // NOI18N
        ImagePanel.add(postgreLabel, "2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void glassfishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassfishButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (ImagePanel.getLayout());
        cl.show(ImagePanel, "0");
    }//GEN-LAST:event_glassfishButtonActionPerformed

    private void javaeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaeeButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (ImagePanel.getLayout());
        cl.show(ImagePanel, "1");
    }//GEN-LAST:event_javaeeButtonActionPerformed

    private void postgresqlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgresqlButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (ImagePanel.getLayout());
        cl.show(ImagePanel, "2");
    }//GEN-LAST:event_postgresqlButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarDenganButtonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarDenganButtonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarDenganButtonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarDenganButtonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarDenganButtonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel GlassfishLabel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel JavaeeLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton glassfishButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JButton javaeeButton;
    private javax.swing.JLabel postgreLabel;
    private javax.swing.JButton postgresqlButton;
    // End of variables declaration//GEN-END:variables
}
