/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package khrisna_p1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class P4_table extends javax.swing.JFrame {
    private int nilaiAkhir;

    /**
     * Creates new form P4_table
     */
    public P4_table() {
        initComponents();
        btn_Hapus.setVisible(false);
        btn_Edit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Simpan = new javax.swing.JButton();
        tf_NIM = new javax.swing.JTextField();
        tf_Nama = new javax.swing.JTextField();
        tf_UTS = new javax.swing.JTextField();
        tf_UAS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mhs = new javax.swing.JTable();
        btn_Edit = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Grade = new javax.swing.JLabel();
        tf_nilaiAkhir = new javax.swing.JTextField();
        tf_grade = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("UTS");

        jLabel4.setText("UAS");

        btn_Simpan.setText("Simpan");
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });

        tf_UTS.setText("  ");

        tbl_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIMl", "Nama", "UTS", "UAS", "Nilai Akhir", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mhs);

        btn_Edit.setText("Edit");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Hapus.setText("Hapus");
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        jLabel5.setText("Nilai Akhir");

        Grade.setText("Grade");

        tf_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_gradeActionPerformed(evt);
            }
        });

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_UTS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(tf_Nama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_NIM, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(tf_UAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Grade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hitung)
                        .addGap(30, 30, 30))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade)
                    .addComponent(tf_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_UTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_UAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Simpan)
                    .addComponent(btn_Edit)
                    .addComponent(btn_Hapus)
                    .addComponent(btn_hitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tbl_mhs.getModel();
        P2_data dtMhs = new P2_data();
        
         String btn = btn_Simpan.getText();
         if(btn == "Simpan"){
             if(tf_NIM.getText().equals("") || tf_Nama.getText().equals("") || tf_UTS.getText().equals("") || tf_UAS.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Input Tidak Boleh Kosong!");
        } else {
            String data[] = {
        tf_NIM.getText(),
        tf_Nama.getText(),
        tf_UTS.getText(),
        tf_UAS.getText(),
        tf_nilaiAkhir.getText(), 
        tf_grade.getText(),
            };
        tblModel.addRow(data);
        tf_NIM.setText("");
        tf_Nama.setText("");
        tf_UTS.setText("");
        tf_UAS.setText("");
        tf_nilaiAkhir.setText("");
        tf_grade.setText("");
        }
         }else{
             int row =tbl_mhs.getSelectedRow();
             tbl_mhs.setValueAt(tf_NIM.getText(), row, 0);
             tbl_mhs.setValueAt(tf_Nama.getText(), row, 1);
             tbl_mhs.setValueAt(tf_UTS.getText(), row, 2);
             tbl_mhs.setValueAt(tf_UAS.getText(), row, 3);
             tbl_mhs.setValueAt(tf_nilaiAkhir.getText(), row, 4);
             tbl_mhs.setValueAt(tf_grade.getText(), row, 5);
             btn_Simpan.setText("Simpan");
         }
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        // TODO add your handling code here:    
DefaultTableModel tblModel = (DefaultTableModel) tbl_mhs.getModel();
        int confirm = JOptionPane.showConfirmDialog(this,"Apakah Anda Yakin Ingin Menghapus Data ini?");
        if(confirm == 0) {
            //yes
            int pilihan = tbl_mhs.getSelectedRow();
            tblModel.removeRow(pilihan);
        }else if(confirm == 1){
        }else{
            
        }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tbl_mhs.getModel();
        int pilihan = tbl_mhs.getSelectedRow();
        tf_NIM.setText(tbl_mhs.getValueAt(pilihan, 0).toString());
        tf_Nama.setText(tbl_mhs.getValueAt(pilihan, 1).toString());
        tf_UTS.setText(tbl_mhs.getValueAt(pilihan, 2).toString());
        tf_UAS.setText(tbl_mhs.getValueAt(pilihan, 3).toString());
        tf_nilaiAkhir.setText(tbl_mhs.getValueAt(pilihan, 4).toString());
        tf_grade.setText(tbl_mhs.getValueAt(pilihan, 4).toString());
        btn_Simpan.setText("Update");
    }//GEN-LAST:event_btn_EditActionPerformed

    private void tbl_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mhsMouseClicked
        // TODO add your handling code here:
        btn_Hapus.setVisible(true);
        btn_Edit.setVisible(true);
        btn_hitung.setVisible(true);
    }//GEN-LAST:event_tbl_mhsMouseClicked

    private void tf_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_gradeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_gradeActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        P2_data dtMHS = new P2_data();
        dtMHS.setNim(tf_NIM.getText());
        dtMHS.setNama(tf_Nama.getText());
        dtMHS.setUts(Double.parseDouble(tf_UTS.getText()));
        dtMHS.setUas(Double.parseDouble(tf_UAS.getText()));
        
        tf_nilaiAkhir.setText(Double.toString(dtMHS.hitungRatarata()));
        
        if(nilaiAkhir>=50){
        tf_grade.setText("E");
        }
        else if(nilaiAkhir>=60){
        tf_grade.setText("D");
        }
        else if(nilaiAkhir>=70){
        tf_grade.setText("C");
        }
        else if(nilaiAkhir>=80){
        tf_grade.setText("B");
        }
            else {
        tf_grade.setText ("A");
        
        }
        
      
    }//GEN-LAST:event_btn_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P4_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P4_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P4_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P4_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P4_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grade;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbl_mhs;
    private javax.swing.JTextField tf_NIM;
    private javax.swing.JTextField tf_Nama;
    private javax.swing.JTextField tf_UAS;
    private javax.swing.JTextField tf_UTS;
    private javax.swing.JTextField tf_grade;
    private javax.swing.JTextField tf_nilaiAkhir;
    // End of variables declaration//GEN-END:variables
}
