/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andri
 */
public class perpustakaan extends javax.swing.JFrame {
    
    model_perpustakaan modelPer;
    DefaultTableModel tblPer;
    
    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
        modelPer = new model_perpustakaan();
        tblPer = (DefaultTableModel) tf_table.getModel();
        refreshTable();
        btn_edit.setVisible(false);
        btn_hapus.setVisible(false);
    }
    
    public void refreshTable() {
        int jumlahRow = tblPer.getRowCount();
        for (int i = jumlahRow - 1; i >= 0; i--) {
            tblPer.removeRow(i);
        }
        
        ResultSet data = modelPer.getAllPer();
        try {
            while(data.next()) {
                tblPer.addRow(new Object[] {
                    data.getString("no"),
                    data.getString("nama"),
                    data.getString("tanggal_pinjam"),
                    data.getString("tanggal_pengembalian"),
                    data.getString("keterangan")
                });
            }
        } catch(SQLException ex) {
            Logger.getLogger(perpustakaan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tf_table = new javax.swing.JTable();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_pinjam = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tf_pengembalian = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_keterangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Tanggal Pinjam", "Tanggal Pengembalian", "Keterangan"
            }
        ));
        tf_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tf_table);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel1.setText("Tanggal Pinjam");

        tf_pinjam.setDateFormatString("yyyy-MM-dd");

        jLabel2.setText("Tanggal Pengembalian");

        tf_pengembalian.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("Nama");

        jLabel4.setText("Keterangan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_pinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_nama)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_keterangan)
                                    .addComponent(tf_pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_simpan)
                            .addComponent(btn_hapus)
                            .addComponent(btn_edit))
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_simpan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_edit)
                        .addComponent(jLabel1))
                    .addComponent(tf_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tf_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btn_hapus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tglPinjam = sdf.format(tf_pinjam.getDate());
        String tglPengembalian = sdf.format(tf_pengembalian.getDate());
        
        modelPer.insertPer(tf_nama.getText(), tglPinjam, tglPengembalian, tf_keterangan.getText());
        
        refreshTable();
        tf_nama.setText("");
        tf_pinjam.setDate(null);
        tf_pengembalian.setDate(null);
        tf_keterangan.setText("");
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tglPinjam = sdf.format(tf_pinjam.getDate());
        String tglPengembalian = sdf.format(tf_pengembalian.getDate());
        
        int row = tf_table.getSelectedRow();
        modelPer.updatePer(tf_nama.getText(), tglPinjam, tglPengembalian, tf_keterangan.getText(), Integer.parseInt((String) tf_table.getValueAt(row, 0)));
        
        refreshTable();
        tf_nama.setText("");
        tf_pinjam.setDate(null);
        tf_pengembalian.setDate(null);
        tf_keterangan.setText("");
        
        btn_simpan.setVisible(true);
        btn_edit.setVisible(false);
        btn_hapus.setVisible(false);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int row = tf_table.getSelectedRow();
        modelPer.hapusPer(Integer.parseInt((String) tf_table.getValueAt(row, 0)));
        refreshTable();
        
        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        
        tf_nama.setText("");
        tf_pinjam.setDate(null);
        tf_pengembalian.setDate(null);
        tf_keterangan.setText("");
        
        btn_simpan.setVisible(true);
        btn_edit.setVisible(false);
        btn_hapus.setVisible(false);
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tf_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_tableMouseClicked
        // TODO add your handling code here:
        int row = tf_table.getSelectedRow();
        Date tglPinjam = null;
        
        try {
            tglPinjam = new SimpleDateFormat("yyyy-MM-dd").parse((String) tf_table.getValueAt(row, 2));
        } catch (ParseException ex) {
            Logger.getLogger(perpustakaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date tglPengembalian = null;
        try {
            tglPengembalian = new SimpleDateFormat("yyyy-MM-dd").parse((String) tf_table.getValueAt(row, 3));
        } catch (ParseException ex) {
            Logger.getLogger(perpustakaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tf_nama.setText(tf_table.getValueAt(row, 1).toString());
        tf_pinjam.setDate(tglPinjam);
        tf_pengembalian.setDate(tglPengembalian);
        tf_keterangan.setText(tf_table.getValueAt(row, 4).toString());
        
        btn_edit.setVisible(true);
        btn_hapus.setVisible(true);
        btn_simpan.setVisible(false);
    }//GEN-LAST:event_tf_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf_keterangan;
    private javax.swing.JTextField tf_nama;
    private com.toedter.calendar.JDateChooser tf_pengembalian;
    private com.toedter.calendar.JDateChooser tf_pinjam;
    private javax.swing.JTable tf_table;
    // End of variables declaration//GEN-END:variables
}
