
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ROZAAN
 */
public class Dzaki_TugasPertemuan4 extends javax.swing.JFrame {

    /**
     * Creates new form Dzaki_TugasPertemuan4
     */
    public Dzaki_TugasPertemuan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        RbJenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LblNim = new javax.swing.JLabel();
        LblNama = new javax.swing.JLabel();
        LblKelamin = new javax.swing.JLabel();
        TxtNim = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        LblSemester = new javax.swing.JLabel();
        TxtSemester = new javax.swing.JTextField();
        LblNilaiKehadiran = new javax.swing.JLabel();
        TxtNilaiKehadiran = new javax.swing.JTextField();
        LblNilaiTugas = new javax.swing.JLabel();
        TxtNilaiTugas = new javax.swing.JTextField();
        LblNilaiUTS = new javax.swing.JLabel();
        TxtNilaiUTS = new javax.swing.JTextField();
        LblNilaiUAS = new javax.swing.JLabel();
        TxtNilaiUAS = new javax.swing.JTextField();
        LblNilaiPemrograman2 = new javax.swing.JLabel();
        TxtNilaiPemrograman2 = new javax.swing.JTextField();
        LblGrade = new javax.swing.JLabel();
        TxtGrade = new javax.swing.JTextField();
        RbLaki = new javax.swing.JRadioButton();
        RbPerempuan = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        BtnHITUNG = new javax.swing.JButton();
        BtnHAPUS = new javax.swing.JButton();
        textArea = new java.awt.TextArea();
        jPanel3 = new javax.swing.JPanel();
        CbxReg = new javax.swing.JCheckBox();
        CbxUts = new javax.swing.JCheckBox();
        CbxUAS = new javax.swing.JCheckBox();
        TxtReg = new javax.swing.JTextField();
        TxtUTS = new javax.swing.JTextField();
        TxtUAS = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        LblNim.setText("NIM");

        LblNama.setText("Nama");

        LblKelamin.setText("J.Kelamin");

        LblSemester.setText("Semester");

        LblNilaiKehadiran.setText("Nilai Kehadiran");

        LblNilaiTugas.setText("Nilai Tugas");

        LblNilaiUTS.setText("Nilai UTS");

        LblNilaiUAS.setText("Nilai UAS");

        LblNilaiPemrograman2.setText("Nilai Pemrograman 2");

        TxtNilaiPemrograman2.setEditable(false);

        LblGrade.setText("Grade");

        TxtGrade.setEditable(false);

        RbLaki.setBackground(new java.awt.Color(204, 204, 204));
        RbJenisKelamin.add(RbLaki);
        RbLaki.setText("Laki-Laki");

        RbPerempuan.setBackground(new java.awt.Color(204, 204, 204));
        RbJenisKelamin.add(RbPerempuan);
        RbPerempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNim)
                            .addComponent(LblNama)
                            .addComponent(LblKelamin))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbLaki)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtNim, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(TxtNama))
                                    .addComponent(RbPerempuan))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblNilaiKehadiran)
                                            .addComponent(LblNilaiTugas)
                                            .addComponent(LblNilaiUTS)
                                            .addComponent(LblNilaiUAS))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtNilaiKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblNilaiPemrograman2)
                                            .addComponent(LblGrade))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtNilaiPemrograman2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(TxtGrade)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblSemester)
                        .addGap(25, 25, 25)
                        .addComponent(TxtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNim)
                    .addComponent(TxtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNilaiKehadiran)
                        .addComponent(TxtNilaiKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNama)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNilaiTugas)
                        .addComponent(TxtNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblKelamin)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNilaiUTS)
                            .addComponent(TxtNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RbLaki))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(RbPerempuan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblNilaiUAS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblSemester)
                        .addComponent(TxtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNilaiPemrograman2)
                            .addComponent(TxtNilaiPemrograman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblGrade)
                            .addComponent(TxtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 0));

        BtnHITUNG.setText("HITUNG");
        BtnHITUNG.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHITUNGActionPerformed(evt);
            }
        });

        BtnHAPUS.setText("HAPUS");
        BtnHAPUS.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHITUNG, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(BtnHAPUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BtnHITUNG)
                .addGap(26, 26, 26)
                .addComponent(BtnHAPUS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 255));

        CbxReg.setBackground(new java.awt.Color(204, 204, 204));
        CbxReg.setText("Reg");

        CbxUts.setBackground(new java.awt.Color(204, 204, 204));
        CbxUts.setText("UTS");

        CbxUAS.setBackground(new java.awt.Color(204, 204, 204));
        CbxUAS.setText("UAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CbxReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtReg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbxUts)
                            .addComponent(CbxUAS))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtUTS, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(TxtUAS))))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxReg)
                    .addComponent(TxtReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxUts)
                    .addComponent(TxtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxUAS)
                    .addComponent(TxtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHITUNGActionPerformed
        // TODO add your handling code here:
        double nilaiPemrograman2 = ((Double.parseDouble(TxtNilaiKehadiran.getText()) * 10) / 100)
                + ((Double.parseDouble(TxtNilaiTugas.getText()) * 20) / 100)
                + ((Double.parseDouble(TxtNilaiUTS.getText()) * 30) / 100)
                + ((Double.parseDouble(TxtNilaiUAS.getText()) * 40) / 100);
        TxtNilaiPemrograman2.setText(Double.toString(nilaiPemrograman2));

        String grade = "E";
        if (nilaiPemrograman2 >= 80) {
            grade = "A";
        } else if (nilaiPemrograman2 >= 70) {
            grade = "B";
        } else if (nilaiPemrograman2 >= 60) {
            grade = "C";
        } else if (nilaiPemrograman2 >= 50) {
            grade = "D";
        } else if (nilaiPemrograman2 < 50) {
            grade = "E";
        }

        TxtGrade.setText(grade);
        int total;
        int biayaReg = Integer.parseInt(TxtReg.getText());
        int biayaUTS = Integer.parseInt(TxtUTS.getText());
        int biayaUAS = Integer.parseInt(TxtUAS.getText());
        total = biayaReg + biayaUTS + biayaUAS;

        String jenisKelamin = "";
        if (RbLaki.isSelected()) {
            jenisKelamin = RbLaki.getText();
        } else {
            jenisKelamin = RbPerempuan.getText();
        }

        // tampilkan nim, nama, jenis_kelamin, semester, nilaiPemrograman2, grade, total
        String isi = "NIM:  " + TxtNim.getText() + "\n"
                + "Nama:  " + TxtNama.getText() + "\n"
                + "Jenis Kelamin:  " + jenisKelamin + "\n"
                + "Semester:  " + TxtSemester.getText() + "\n"
                + "Nilai Pemrograman 2:  " + nilaiPemrograman2 + "\n"
                + "Grade:  " + grade + "\n"
                + "Total:  " + total + "\n";
        textArea.setText(isi);
    }//GEN-LAST:event_BtnHITUNGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dzaki_TugasPertemuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dzaki_TugasPertemuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dzaki_TugasPertemuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dzaki_TugasPertemuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dzaki_TugasPertemuan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHAPUS;
    private javax.swing.JButton BtnHITUNG;
    private javax.swing.JCheckBox CbxReg;
    private javax.swing.JCheckBox CbxUAS;
    private javax.swing.JCheckBox CbxUts;
    private javax.swing.JLabel LblGrade;
    private javax.swing.JLabel LblKelamin;
    private javax.swing.JLabel LblNama;
    private javax.swing.JLabel LblNilaiKehadiran;
    private javax.swing.JLabel LblNilaiPemrograman2;
    private javax.swing.JLabel LblNilaiTugas;
    private javax.swing.JLabel LblNilaiUAS;
    private javax.swing.JLabel LblNilaiUTS;
    private javax.swing.JLabel LblNim;
    private javax.swing.JLabel LblSemester;
    private javax.swing.ButtonGroup RbJenisKelamin;
    private javax.swing.JRadioButton RbLaki;
    private javax.swing.JRadioButton RbPerempuan;
    private javax.swing.JTextField TxtGrade;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNilaiKehadiran;
    private javax.swing.JTextField TxtNilaiPemrograman2;
    private javax.swing.JTextField TxtNilaiTugas;
    private javax.swing.JTextField TxtNilaiUAS;
    private javax.swing.JTextField TxtNilaiUTS;
    private javax.swing.JTextField TxtNim;
    private javax.swing.JTextField TxtReg;
    private javax.swing.JTextField TxtSemester;
    private javax.swing.JTextField TxtUAS;
    private javax.swing.JTextField TxtUTS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.TextArea textArea;
    // End of variables declaration//GEN-END:variables
}
